### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by lemointm** [Rolleroo/decaychain#1]
Hi! I am very interested in your package to calculate abundances of decay products. Do you have plans for python 3.7 support? Thanks!

**Comment by Rolleroo** [comment]
Hi there. Unfortunately I haven't updated this for a while and won't get round to it for some time.

An alternative would be the package by Alex Malins.

https://github.com/alexmalins/radioactivedecay

We did some cross checking against each one. Alex's code is more elegant but doesn't have the capacity to change the half-life data so easily, we'll it didn't when I last looked.

Kenny

**Comment by lemointm** [comment]
No worries, thanks Kenny! Alex and I have been looking into some updates for his code to get abundance calculations working, I hope to have a PR in soon.

Thom
